#!/bin/bash

# make -f $REDBUILD/Makefile $@

cred build.redb -o build.c

FW=""

if [ "$(uname)" = "Darwin" ]; then
    FW="-framework Cocoa -framework IOKit -framework CoreVideo -framework CoreFoundation"
fi

gcc build.c $HOME/redbuild/redbuild.c -I. -I../redbuild -I../os/shared ../os/shared/clibshared.a ../redxlib/redxlib.a ../raylib/src/libraylib.a -lm -lc $FW -o build