#!/bin/bash

ccommands(){
    bear -- make -f $REDBUILD/Makefile -B
}

publish(){
    cp $REDBUILD/Makefile ./Makefile
}

if [ "$1" == "bear" ]; then
    ccommands
elif [ "$1" == "publish" ]; then
    publish
fi