#!/bin/bash

if [ "$SHELL" = "/bin/zsh" ]; then
    CONFIG_FILE="$HOME/.zshrc"
else
    CONFIG_FILE="$HOME/.bashrc"
fi

echo "export REDBUILD=$(pwd)" >> "$CONFIG_FILE"
echo "export PATH=\$PATH:$(pwd)/utils" >> "$CONFIG_FILE"

source $CONFIG_FILE