#!/bin/bash

echo "Initializing [REDACTED] project"

cp $REDBUILD/package.info $(pwd)/package.info

cp $REDBUILD/gitignore $(pwd)/.gitignore

mkdir -p $(pwd)/resources

echo "[REDACTED] project created"
